### ISSUE TITLE
triggerTransform example results in very hard-to-find error

### ISSUE THREAD

**Issue by thebigredgeek** [davidyaha/graphql-redis-subscriptions#11]
After spending about 4 hours debugging a weird error where I was getting the message `Cannot convert undefined or null to object` as a message back from the WS subscribe query, I discovered that it was caused by the transpiled version of the triggerTransform example in the README:

```js
function triggerTransform(trigger, _ref) {
  var path = _ref.path;
  return [trigger].concat(_toConsumableArray(path)).join('.');
}
```

After doing a bit of manual debugging, I discovered that the error was being thrown along this path:

[Point #1](https://github.com/apollostack/graphql-subscriptions/blob/master/src/pubsub.ts#L211)
[Point #2](https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/redis-pubsub.ts#L38)

The triggerTransform function is, of course, the transpiled function pasted above which is the `triggerTransform` example in the README.  It looks like the problem is that `_ref.path` is actually undefined.  The `trigger` parameter is equal to a string (the channel name), and `_ref` (which is the value from `{path}` as the second param in the example) is undefined because the [options object in the function header](https://github.com/davidyaha/graphql-redis-subscriptions/blob/master/src/redis-pubsub.ts#L37) is an empty object for whatever reason (presumably a default option from [here](https://github.com/apollostack/graphql-subscriptions/blob/master/src/pubsub.ts#L175)).

I was able to pinpoint the source by wrapping the transpiled code of both of the functions listed above in try/catch blocks and tracing out the errors.

Wondering if this is an error with the docs or a regression somewhere else, like in the coupling between this library and [graphql-subscriptions](https://github.com/apollostack/graphql-subscriptions)?

**Comment by davidyaha** [comment]
@thebigredgeek Actually I think the problem is that the docs are not clear about the fact that it's the implementors responsibilty to write both how the channel would get the `options` object. (taken from `channelOptions` on every channel via the [`setupFunctions` param](https://github.com/apollostack/graphql-subscriptions/blob/master/src/pubsub.ts#L83-L98)) In what form, and also he should implement the `triggerTranform` which accepts the options object a second param right after the explicit trigger param.

The example does show this very crucial part:
```
const subscriptionManager = new SubscriptionManager({
  schema,
  setupFunctions: {
    commentsAdded: (options, {repoName}) => ({
      'comments.added': {
        channelOptions: {path: [repoName]},
      },
    }),
  },
  pubsub,
});
```

Where you can see that I return the `channelOptions` object, synthesized to my own satisfaction...
The thing is that I would like to keep to example as simple as possible, I should maybe just move that part of the readme to somewhere else with more explicit directions.

Thanks alot for your feedback!

**Comment by thebigredgeek** [comment]
@davidyaha  Ah gotcha gotcha.  Yeah the docs for graphql-subscriptions definitely aren't clear.  I was hoping to contribute to them but it looks like the docs aren't in the repo :(

**Comment by davidyaha** [comment]
@thebigredgeek is it ok to close that issue?

**Comment by thebigredgeek** [comment]
@davidyaha it might be a good idea to satisfy this issue with docs, and close it once docs are implemented?
