### ISSUE TITLE
Group graphql executions when possible

### ISSUE THREAD

**Issue by Shahor** [davidyaha/graphql-redis-subscriptions#120]
Hello!

I'm building a real time application with graphql subscriptions and I am facing performance issues at the moment.

What I do is I use the graphql subscriptions more like a contract than for it's resolvers per say.

The data I want to pass through to the connected clients is precomputed and I know my audience from the start, therefore I don't need to run the graphql execution for as many sockets as I have connected.

Once per payload is enough, and I could just use the result of that execution to all the users (the resolvers don't do anything related to the user so it doesn't matter really).

I have been trying to implement this but I think I'm missing something and don't understand exactly how/where I could do it.

Would you mind giving me some pointers so I can implement it?
I think this is really critical for subscriptions performances, and could spend some time on it given some help.

**Comment by davidyaha** [comment]
Hey @Shahor! 
Thanks again for your interest.

I'll try to help if I can as performance is key 😄 
First off, the reason for this library is that as graphql execution could be costly for realtime data, scaling horizontally allows dealing with the time it takes to run execution in general and generic way.
This is the whole point of this library, taking an event from graphql-subscriptions and publishing it through redis pubsub mechanism so it can be executed on various machines.

So just to explain better the functionality here:

1. Client1 -> subscribes to Entity1 -> GQL1 -> subscribes on Entity1 - > Redis1
2. Client2 -> subscribes to Entity1 -> GQL2 -> subscribes on Entity1 -> Redis2
3. Client3 -> mutates Entity1 -> GQL3 -> executes mutation and publishing Event1 -> Redis2
4. Redis2 -> publishes Event1 -> GQL2 -> executes subscription query and publishing ModifiedEvent1 -> Client2
5. Redis2 -> publishes Event1 -> Redis1 -> publishes Event1 -> GQL1 -> executes subscription query and publishing ModifiedEvent2 -> Client1

This way the event gotten executed on for all subscribers on their graphql servers, allowing to distribute the load. This does introduce more hops of the data and so may cause greater latency if not configured correctly and also if the amount of clients are quite small, it may be redundant.

If you have less then say, 1,000 completely different events per second and under 10 clients (default limit on Node's EventEmitter, can be increased) it's be better to stick with one GraphQL server and execute the event query there.

In your case, you would like to actually proxy the processed event as-is to all of your clients so I think that your best option is to actually just wrap graphql-js execute function 
 so that the subscriptions-transport-ws will not execute the query in full for each client. You can see [here](https://github.com/apollographql/subscriptions-transport-ws#constructoroptions-socketoptions) that the transport does let you provide this execute as an option, so it will be easy implement and plug in.
I guess you can just check if the query and event are equal to something you have already in a WeakMap and just return the value rather then calling execute on each execute call.
I do think this code belongs either on your app in particular, or on a separate package. 

I hope this helps in any way, and I'd love to chime in if you do create a package out of that code so make sure to add it in this thread.

Best of luck to you good sir! 🎩

**Comment by Shahor** [comment]
The architecture I have as of today is kind of that :) 

I have one Redis publishing events, and every worker process is subscribing to Redis and executes the query for the clients connected.

That way we can scale horizontally without a problem, but I'm looking at how to improve the performance of our worker in order to ensure we scale horizontally for the good reasons :) 

At the moment my process is choking on 60 000 events/s with 300 connections per process (average) and that doesn't seem to be acceptable.

I have yet to setup a process that only acts as a proxy to the connected sockets to see how many could be handled with the smallest setup possible, but in the meantime I know I can improve that (because I analyzed the issue) by reducing the GC passes, and that's doable by performing the graphql execution only once per payload 🎉 

In order to confirm my theory I basically have a bucket of sockets + a `WeakMap` of the payloads I receive and I deal with them in the `withFilter`callback by writing directly the payload (1 graphql execution isn't going to change much here) to each socket in my bucket, and always returning false in `withFilter`.

That's dirty but it allowed me to validate my assumptions so I'm now going to implement this thanks to the `execute` parameter.

One thing I had with this though is that when I tried replacing the `execute` function with something like 

```js
execute : (...args) => {
debugger
return execute(...args)
}
```

And the `debugger` never got called :( 

Is that wrong in some way or something?

**Comment by Shahor** [comment]
Well, according to [this line](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L342) one should use the `subscribe` function only, but then why does the doc state that we should also give the `execute` function to a subscriptions transports... 🤔? That's weird :D
