### ISSUE TITLE
Event loop blocked by too many executions

### ISSUE THREAD

**Issue by Shahor** [davidyaha/graphql-redis-subscriptions#173]
Hello 👋 

I have noticed something weird I would like to discuss with you for I'm not certain of its origin and am not comfortable enough with asyncIterators to diagnose this properly.

My apologies if this doesn't come from the redis-subscriptions package.

Using this [reproduction repo](https://github.com/Shahor/subscriptions-example) you can:
- set up a server accepting websocket connections
- set up 300 websocket connections
- publish 500 messages into redis to be computed

Doing this, you should obtain the [following behavior](https://imgur.com/k5JIQU2)

I am a bit confused as to why the event loop would be blocked. Is there an operation that should be async that isn't?

You can see this happen as well if the `filterFn` in `server/index.js:49` returns false so that nobody is interested in spinning the graphql execution for this message. (You might have to send more messages to witness it, `node publisher/index.js 1000`)

Is it possible that this comes from this package, or should I rather be looking into https://github.com/apollographql/subscriptions-transport-ws ?

While I realize this makes for a lot of messages to be handled by the process
> Each message triggers 300 potential executions, this makes for 150 000 graphql executions to be performed
I would expect the whole process to be slow, but not for the event loop to be totally blocked.

This is especially true when we return `false` in the `filterFn` function (which means the issue doesn't come from the graphql layer)

**Comment by davidyaha** [comment]
Hey @Shahor!

As far as I understand it, this package is could not be the issue as this package will only tackle those 500 messages sent to the node instance from Redis. Those messages will be accumulated in an AsyncIterable and then will be read and executed by the subscriptions server.

In order to be sure I'd have to dig in on your repo. Is there any more information that you've discovered since opening the issue?

Regardless, I suspect that the problem you are facing is inherent with how `subscriptions-transport-ws` reads each event from the AsyncIterable and the limitations of a single node process while sending information over a web socket. 

As you can see here https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L373 the server uses `forAwaitEach` which will wait for the next event to be pushed into the iterable.

Basically, in your scenario, you've created 300 subscribers that are waiting to get a new message.
When the first message arrives, the server will start formatting and pushing those messages down each of the 300 open channels and while those are not synchronous work, it will choke the event loop quite easily.

These kinds of issues are actually the reason why I've created this library, to allow for horizontal scaling on the servers doing the execution work.

The thing that does not make sense and could definitely be an issue, is that you saying that the filter returns false and still it does not decrease the amount of work the server deals with... Unless the whole pressure does not come from there.

I'll try running the thing myself and see if I arrive at any conclusion but thanks for raising that up.
