### ISSUE TITLE
Add option to use existing redis connection for publish events

### ISSUE THREAD

**Issue by hems** [davidyaha/graphql-redis-subscriptions#69]
Hello, i'm still halfway implementing my subscription one thing i noticed is that there was no example ( that i could find ) for peeps using an already existing Redis connection.

For instance in my case before creating the RedisPubSub i already have a connection to redis happening on my application:
````
  client = redis.createClient({
    url: url,
    db : db
  })
````

So i'm wondering if using this object as "connection" parameter for the PubSub will be enough for it to "reuse" my existing connection, as in:
````
var pubsub = new RedisPubSub({
  connection      : client,
  triggerTransform: transform
})
````

Is that supposed to work, if not how would i go about this ?

**Comment by davidyaha** [comment]
Hey @hems!

Thanks for taking interest in this project!
The packages uses two redis connections because of a limit with redis where a "Subscribe"ing connection cannot issue any other methods. 
https://redis.io/commands/subscribe

For the publish event, it should be possible to supply a connection from the options object so if you PR this feature I'll happily merge it.

Currently the `connection` field is probably wrongly named but let's keep it this way so it will not break current implementations.
You can add a TODO for renaming in future releases. 
Thanks again!

**Comment by hems** [comment]
I didn't know we would need a new connection, makes more sense now!
