### ISSUE TITLE
Subscriptions stacking with each deploy

### ISSUE THREAD

**Issue by mxstbr** [davidyaha/graphql-redis-subscriptions#94]
The subscriptions stack in Redis every time we deploy our server, meaning by now every message is sent five times to every user that's subscribed.

Any ideas why that's happening? What are we doing wrong?

**Comment by davidyaha** [comment]
Hey @mxstbr!
Thanks for taking interest in this library!

Do you have a way to reproduce on gist or better yet, in the tests files?
Also, how many subscriber servers are we talking about?
Is there any "hot" replacement that makes the redis think a certain subscriber is still connected whilst it has switched to another?
Are you using sentinel or any saas redis solutions?

Thanks ahead for the answers, I hope this is resolved quickly!

**Comment by mxstbr** [comment]
>  Also, how many subscriber servers are we talking about?

Anywhere from 1 to 15.

> Is there any "hot" replacement that makes the redis think a certain subscriber is still connected whilst it has switched to another?

The server scales multiple instances automatically up and down based on usage (we use now.sh for deployment), but that isn't "hot" I don't tink?

>  Are you using sentinel or any saas redis solutions?

Yes, compose.io.

Unfortunately I don't really know how to submit a test case for this, I was hoping you'd encountered that problem before. 😅

**Comment by mxstbr** [comment]
Okay so this only happens with concurrent instances, it's contrary to our initial intuition not every historic deploy ever made.

Any ideas why concurrently running two instances of `graphql-redis-subscriptions` would mean that each message is sent twice?

**Comment by mxstbr** [comment]
Basically, this is what we have:

```
+---------------------------------------+
|                                       |
|                 Redis                 |
|                                       |
+-------^----------------------^--------+
        |                      |
        |                      |
+----------------+     +----------------+
|                |     |                |
|   Instance 1   |     |   Instance 2   |
|                |     |                |
+-^----------^---+     +-^---------^----+
  |  |       | |         | |       |  |
  |  |       | |         | |       |  |
+----v-+   +---v--+   +----v-+   +----v-+
| User |   | User |   | User |   | User |
+------+   +------+   +------+   +------+
```

Multiple instances of the same server between which load is automatically distributed. (meaning each user is subscribed via GraphQL subscriptions to one of those instances) When only one instance is running everything is fine and every user that is subscribed gets every message once.

As soon as there are two instances though, every message that is sent down live gets sent twice by the same instance. :thinking: 

Does that make sense?

**Comment by davidyaha** [comment]
Hmm... Could it be that the mutations / event source is being published twice? maybe due to LB strategy?
Are you using the websocket transport for users?
Does these server instances subscribe to the same channels? Is there any filtering happening using the channel name?

Sorry I am not very responsive, I am at holiday and getting very brief moments of wifi connection..

**Comment by mxstbr** [comment]
No worries, I appreciate the responses!

> Could it be that the mutations / event source is being published twice? maybe due to LB strategy?

I don't know what "LB Strategy" means. We're using RethinkDB changefeeds to subscribe to changes in the database. Theoretically each user is subscribed to one instance, and that instance has it's own changefeed/listener, so it should not be published twice.

>  Are you using the websocket transport for users?

Yeah, the Apollo stack: `graphql-transport-ws` and `graphql-subscriptions`. 

> Does these server instances subscribe to the same channels? Is there any filtering happening using the channel name?

Yes, we do some filtering. This is what a subscription looks like, slightly simplified:

```JS
module.exports = {
  Subscription: {
    messageAdded: {
      resolve: message => message,
      subscribe: withFilter(
        // pubsub === graphql-redis-subscriptions
        () => pubsub.asyncIterator(MESSAGE_ADDED),
        async (message, { thread }, { user }) => {
          // Message was sent in different thread, early return
          if (message.threadId !== thread) return false;

          // Make sure the subscribed user can view that thread
          return await userCanViewThread(message.threadId, user.id)
        }
      ),
    },
  },
};
```

**Comment by mxstbr** [comment]
Hey @davidyaha any ideas what the issue could be here?

**Comment by davidyaha** [comment]
So to my understanding, the rethink changefeed is the issue most probably.
I would explain the flow of the issue like so: (Just a theory and needs to be validated)
- **User A** subscribes to **GQL-X** with subscription "messageAdded" and threadId 1
- **GQL-X** subscribes to **Redis** with channel name "message-added" (no filtering on redis channel right?)
- **GQL-X** opens **rethink** changefeed listener (What is the filtering there?)
- **User B** subscribes to **GQL-Y** with subscription "messageAdded" and threadId 1
- **GQL-Y** subscribes to **Redis** with channel name "message-added"
- **GQL-Y** opens **rethink** changefeed listener (What is the filtering there?)
- **User A** adds a message - calls mutation on **GQL-X**
- **GQL-X** updates **rethink** db messages table
- **rethink** publishes change on messages changefeed
- **GQL-X** gets the message added change from **rethink**
- **GQL-Y** gets the message added change from **rethink**
- **GQL-X** publish on **redis** "message-added" channel the changed message
- **GQL-Y** publish on **redis** "message-added" channel the changed message
- **GQL-X** received from **redis** _**two**_ messages  from "message-added" channel
- **GQL-Y** received from **redis** _**two**_ messages  from "message-added" channel
- **GQL-X** published to **User A** _**two**_ message on "messageAdded" subscription
- **GQL-Y** published to **User B** _**two**_ message on "messageAdded" subscription

I might be wring in any of the steps or my assumption of your environment so please correct my mistakes on that example so we will have common grounds.

If this makes sense, I would actually get rid of the redis and just wrap the changefeed listener with a AsyncIterable object and pass that to the `withFilter` function.
Otherwise you are doing the same thing (share events between instances) on both redis and rethink.

I am back at the office now so I am more responsive so let me know how it goes!

**Comment by mxstbr** [comment]
No you're totally right, only the changefeed is opened per server instance not per-user, but that's a minor nitpick.

Now that you lay it out like that it makes absolute sense that it would get two messages from a subscription. I don't know why we didn't just wrap the RethinkDB changefeed in an async iterable, I'll just try that now 😅 

Thank you for the responses and helping me figure this out, will report back with results!

**Comment by davidyaha** [comment]
Great! I really hope that's it and we will maybe have a new "RethinkDB" pubsub to work with 😄 
If you do end up writing and publishing it, please let me know and I'll add it on the readme here.

Good luck!
